przyprawy = ['herbaty', 
'biedrzeniec', 'anyż','kminek', 
'kolendra','fenkuł', 
'koper', 'ogrodowy' ,'kmin', 'rzymski', 'kminek',
'adżwan','selery', 
'badian',  'anyż' 'gwiaździsty',
'berberys',
'borówka', 'brusznica',
'chmiel',
'cytrus', 
'dereń', 
'granatowiec', 
'jałowiec', 
'jarząb', 
'korzennik', 
'papryka',
'pieprz', 'cayenne',
'pieprz',
'pieprz', 'długi',
'pieprz', 'kubeba',
'pomidor' 
'keczup',
'rokitnik',
'róża', 'dzika',
'sumak', 'garbarski',
'wanilia', 
'wawrzyn', 
'winorośl', 
'czarnuszka',
'gorczyca',
'gorczyca',
'kardamon',
'kakao',
'kola',
'kozieradka',
'mak',
'migdały', 'marcepan',
'gałka', 'muszkatołowa',
'rukola',
'sezam',
'sos', 'sojowy',
'bez',
'goździki',
'kapary',
'ketmia', 'szczawiowa',
'szafra',
'chrzan',
'cykoria',
'dzięgiel', 'litwor',
'arcydzięgiel', 'litwor',
'imbir', 'lekarski',
'Kaempferia',
'lukrecja',
'kurkuma', 
'szafran', 
'tatarak',
'cebula',
'szczypiorek',
'czosnek',
'por',
'cynamon',
'bazylia',
'liście', 'curry',
'estragon',
'piołun',
'cząber',
'cząber',
'hyzop',
'koper', 'koperek',
'lawenda',
'majeranek',
'chmiel',
'oregano',
'lubczyk', 'maggi',
'tymianek',
'tymianek', 
'tymianek', 'saturejski',
'tymianek', 'mastix',
'melis',
'mięta',
'trawa', 'cytrynowa',
'pietruszka',
'rzeżucha',
'pokrzywa',
'portulaka', 
'przytulia',
'roszponka', 
'rozmaryn',
'ruta',
'szałwia','szczaw','trybula',
'liście', 'bobkowe','liście',
'laurowe','wrotycz', 'balsamiczny', 
'wrotycz', 'pospolity',
'bez', 
'borówka', 'czernica',
'brzoza',
'głóg', 'dwuszyjkowy',
'głóg', 'jednoszyjkowy',
'jałowiec', 'pospolity',
'kasztanowiec', 'zwyczajny',
'krwawnik', 'pospolity',
'lipa',
'mniszek', 
'podbiał', 
'pokrzywa', 
'róża', 'dzika',
'bazylia', 
'fenkuł', 'włoski',
'kminek', 
'konwalia', 'majowa',
'kozłek',
'mięta', 'pieprzowa',

'majeranek', 
'prawoślaz', 
'rumianek', 
'szałwia', 
'tymianek', 
'miłorząb',
'dzika', 'róża',
'głóg',
'dziurawiec',
'rumianek',
'karczoch',
'aloes',
'aronia',
'hakorośl', 'rozesłana',
'żeń-szeń',
'melisa',
'tymianek',
'męczennica', 'cielista',
'aspalat', 'prosty',
'ostropest', 'plamisty',
'bez'] 

warzywa = ['kokosowe', 'cebula', 'perłowa',
'cebula', 'zwyczajna',
'czosnek', 'pospolity',
'por',
'czosnek', 'rokambuł',
'czosnek', 'askaloński', 'szalotka',
'czosnek', 'dęty', 'cebula', 'siedmiolatka',
'szczypiorek',
'burak', 'liściowy', 'boćwina',
'burak', 'ćwikłowy', 'botwina',
'cykoria', 'sałatowa',
'cykoria', 'endywia',
'pietruszka', 'naciowa',
'portulaka', 'pospolita', 'warzywna',
'roszpunka', 'warzywna',
'pieprzyca', 'siewna', 'rzeżucha', 'ogrodowa',
'rukiew', 'wodna',
'sałata', 'siewna',
'seler', 'naciowy',
'szpinak', 'warzywny',
'trętwian', 'czterorożny', 'szpinak', 'nowozelandzki',
'rokietta', 'siewna', 'rukola',
'mniszek', 'pospolity', 'lekarski',
'wilec', 'ziemniaczany', 'batat',
'burak', 'ćwikłowy',
'maniok', 'jadalny',
'maranta', 'trzcinowa',
'marchew', 'zwyczajna',
'pasternak', 'zwyczajny',
'pietruszka', 'korzeniowa',
'salep',
'kozibród', 'porolistny', 'salsefia',
'seler', 'korzeniowy',
'słonecznik', 'bulwiasty', 'topinambur',
'wężymord', 'czarny', 'korzeń', 'skorzonera',
'oberżyna', 'bakłażan',
'papryka', 'roczna',
'pomidor', 'zwyczajny',
'pomidor', 'koktajlowy',
'ziemniak',
'miechunka', 'peruwiańska', 'rodzynek', 'brazylijski',
'miechunka', 'pomidorowa',
'kabaczek',
'cukinia',
'patison',
'dynia', 'zwyczajna',
'dynia', 'olbrzymia',
'melon',
'ogórek', 'siewny',
'arbuz', 'zwyczajny', 'kawon',
'brukiew', 'karpiel',
'rzepa',
'rzodkiew', 'zwyczajna', 'rzodkiew',
'rzodkiewka',
'rzodkiew', 'japońska', 'daikon',
'bób',
'ciecierzyca', 'pospolita',
'fasola', 'zwykła',
'fasola', 'wielokwiatowa',
'groch', 'zwyczajny',
'soczewica', 'jadalna',
'soja', 'warzywna',
'chrzan', 'pospolity',
'rabarbar', 'ogrodowy',
'szczaw', 'zwyczajny',
'szparag', 'lekarski',
'cząber', 'ogrodowy',
'kminek', 'zwyczajny',
'koper', 'ogrodowy',
'lebiodka', 'majeranek', 'majeranek', 'ogrodowy',
'kapary', 'cierniste', 'kapary',
'karczoch', 'zwyczajny',
'karczoch', 'hiszpański', 'kard',
'kukurydza', 'cukrowa',
'oliwka', 'europejska',
'pochrzyn', 'chiński',
'pieczarka',
'pieprznik', 'jadalny',
'borowikowate',
'trufle',
'uszak',
'trzęsak',
]

nabial = [
'mleko', 'skondensowane',
'mleko', 'proszku',
'niefermentowane', 'napoje', 'mleczne', 'mleko', 'kakaowe', 'koktajle', 'mleczne',
'fermentowane', 'napoje', 'mleczne', 'jogurt', 'kefir', 'kumys',
'śmietanka',
'śmietana',
'ser', 'twarogowy',
'ser', 'podpuszczkowy'
]

zboza = ['ryżu', 'makaronu', 'amarantus', 'szarłat', 'mąka', 'amarantusa', 'nasiona', 'amarantusa', 'płatki', 'amarantusowe', 'gryka', 'zwyczajna', 'mąka', 'gryczana', 'kasza', 'gryczana', 'prażona', 'biała', 'płatki', 'gryczane', 'kasza', 'gryczana', 'łamana', 'prażona', 'biała', 'kasza', 'gryczana', 'łamana', 'drobna', 'biała', 'krakowska', 'otręby', 'gryczane', 'jęczmień', 'mąka', 'jęczmienna', 'tsampa', 'pęczak', 'pęczak', 'obtaczany', 'kujawski', 'płatki', 'jęczmienne', 'kasza', 'jęczmienna', 'łamana', 'wiejska', 'kasza', 'perłowa', 'mazurska', 'kasza', 'perłowa', 'prażona', 'komosa', 'ryżowa', 'kukurydza', 'mąka', 'kukurydziana', 'masa', 'harina', 'skrobia', 'kukurydziana', 'ziarna', 'kukurydzy', 'płatki', 'kukurydziane', 'kasza', 'kukurydziana', 'popcorn', 'syrop', 'glukozowo','fruktozowy', 'kiełki', 'kukurydzy', 'kotewka', 'orzech', 'wodny', 'płatki', 'orzechami', 'wodnymi', 'owies', 'mąka', 'owsiana', 'pęczak', 'owsiany', 'płatki', 'owsiane', 'kasza', 'owsiana', 'łamana', 'otręby', 'owsiane', 'proso', 'mąka', 'jaglana', 'kasza', 'jaglana', 'płatki', 'jaglane', 'pszenica', 'mąka', 'pszenna', 'mąka', 'grahama', 'krupczatka', 'mąka', 'orkiszowa', 'mąka', 'orkiszowa', 'razowa', 'pęczak', 'pszenny', 'pęczak', 'orkiszowy', 'płatki', 'pszenne', 'płatki', 'orkiszowe', 'kasza', 'manna', 'semolina', 'kasza', 'orkiszowa', 'otręby', 'pszenne', 'otręby', 'orkiszowe', 'kuskus', 'bulgur', 'zarodki', 'pszenne', 'kiełki', 'pszenicy', 'pszenżyto', 'mąka', 'pszenżytnia', 'ryż', 'mąka', 'ryżowa', 'ryż', 'długoziarnisty', 'ryż', 'średnioziarnisty', 'ryż', 'krótkoziarnisty','ryż', 'biały', 'częściowo', 'szlifowany', 'ryż', 'biały', 'dobrze', 'szlifowany', 'ryż', 'brązowy', 'ryż', 'preparowany', 'termicznie', 'parboiled', 'ryż', 'błyskawiczny', 'ryż', 'glazurowany', 'płatki', 'ryżowe', 'ryż', 'biały', 'łamany', 'otręby', 'ryżowe', 'ryż', 'dęty', 'sorgo', 'mąka', 'sorgo', 'kasza', 'sorgo', 'miód', 'sorgowy', 'teff', 'mąka', 'teffu', 'włośnica', 'ber', 'czumiza', 'kasza', 'włośnicy', 'żyto', 'mąka', 'żytnia', 'otręby', 'żytnie', 'kiełki', 'żytnie']

tluszcze = ['tłuszcze', 'roślinne', 'olej', 'andiroba', 'orzechów', 'arachidowych', 'arganowy', 'awokado', 'babassu', 'nasion', 'bawełny', 'pestek', 'brzoskwini', 'calophyllum', 'czarnej', 'porzeczki', 'czarnuszki', 'czaulmugrowy', 'pestek', 'dyni', 'dzikiej', 'róży', 'nasion', 'gorczycy', 'nasion', 'herbaty', 'tsubaki', 'kapokowy', 'kminkowy', 'konopny', 'krokosza', 'barwierskiego', 'krotonowy', 'kukurydziany', 'lniany', 'orzeszków', 'makadamii', 'makowy', 'mangowy', 'migdałowy', 'miodli', 'indyjskiej', 'pestek', 'moreli', 'neem', 'niger', 'ogórecznika', 'lekarskiego', 'oliwkowy', 'oliwa', 'orzechów', 'ziemnych', 'orzechów', 'laskowych', 'orzecha', 'włoskiego', 'nasion', 'ostu', 'pistacjowy', 'nasion', 'pomidorów', 'kiełków', 'pszenicy', 'rokitnikowy', 'rycynowy', 'rącznika', 'ryżu', 'rzepakowy', 'sezamowy', 'słonecznikowy', 'sojowy', 'kwiatu', 'szafranu', 'nasion', 'tytoniu', 'nasion', 'wiesiołka', 'pestek', 'winogron', 'żurawiny', 'błotnej', 'masło', 'kakaowe', 'drzewny', 'jojoba', 'kokosowy', 'masło', 'kokosowe', 'palmowy', 'tokoferol', 'masłosza', 'Parka', 'masło', 'shea']

jednostki = [
    'łyżeczki',
    'łyżki',
    'szklanki',
    'szczypta',
    'ząbek',
    'garść',
    'l',
    'ml',
    'g',
    'kawałki',
    'puszka',
    'opakowanie',
    'karton',
    'filiżanka',
    'gałązka',
    'cząstka',
    'liści',
    'plastry',
    'sztuk',
    'owoców',
    "ćwiartki",
    'saszetki',
    'główka',
    'nasion',
    'miseczka',
    'bulwy'  
]